version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app # Monta el directorio actual para desarrollo (opcional para producción)
      - media_files:/app/media # Volumen persistente para archivos media
    ports:
      - "8000:8000"
    env_file:
      - .env # Carga variables de entorno desde el archivo .env
    depends_on:
      - db
    environment:
      # Sobrescribe DB_HOST para el entorno de Docker Compose para usar el nombre del servicio
      DB_HOST: db
    command: gunicorn cartera_clientes.wsgi:application --bind 0.0.0.0:8000 --timeout 240 # Añade o modifica esta línea
    # <<-- ESTA LÍNEA 'deploy:' DEBE TENER SOLO 2 ESPACIOS DE INDENTACIÓN -->>


    deploy:
      resources:
        limits:
          memory: 2084m  # Intenta con 512MB
        reservations:
          memory: 512m # Puedes reservar un mínimo de memoria también
    networks:
      - nginx_default

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql # Volumen de datos persistente para la base de datos
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nginx_default

volumes:
  db_data: # Define el volumen nombrado para la persistencia de la base de datos
  media_files:
    external: true
    name: crm-iamet_media_files  # Volumen REAL con todo el Drive de oportunidades (~9.9GB)

# Añade esta sección al final del archivo
networks:
  nginx_default:
    external: true