"""
Django settings for cartera_clientes project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables de entorno desde .env en el directorio raíz del proyecto
dotenv_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=dotenv_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Obtén la SECRET_KEY de las variables de entorno
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-%bvhvsoqj7(y%nvdm!*_u26-x3kc$3!f&d#8*j#km!j=g%@iye') # Valor por defecto para desarrollo si no está en .env

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True' # Lee DEBUG de las variables de entorno

# En producción, esto debe contener los dominios de tu sitio (ej. ['tudominio.com', 'www.tudominio.com'])
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,nethive.mx,www.nethive.mx,v488452.neubox.net,ns1.rctecnologia.com.mx').split(',') # Lee ALLOWED_HOSTS de las variables de entorno
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1,https://bajanet.bitrix24.mx').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'app', # ¡Asegúrate de que tu aplicación 'app' esté listada aquí!
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuración de seguridad adicional para producción
# if not DEBUG:
#     # Redirigir todo el tráfico HTTP a HTTPS
#     SECURE_SSL_REDIRECT = True
#     # HSTS (HTTP Strict Transport Security) para forzar HTTPS en futuras visitas
#     SECURE_HSTS_SECONDS = 31536000  # 1 año
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True
#     # Protección contra ataques XSS en navegadores antiguos
#     SECURE_BROWSER_XSS_FILTER = True
#     # Protección contra ataques de "content sniffing"
#     SECURE_CONTENT_TYPE_NOSNIFF = True
#     # Protección contra clickjacking
#     X_FRAME_OPTIONS = 'DENY'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuración de cookies para iframes y cross-site requests
if not DEBUG:
    # Configuración para producción (HTTPS)
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False  # Necesario para que JavaScript pueda acceder al token CSRF
    # Configuración adicional para cross-site requests
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Permite iframes del mismo origen
else:
    # Configuración para desarrollo local (HTTP)
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False

ROOT_URLCONF = 'cartera_clientes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # 'DIRS': [] está bien si 'APP_DIRS': True
        'APP_DIRS': True, # ¡Muy importante! Le dice a Django que busque plantillas en las carpetas 'templates' de tus apps.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.supervisor_flag',
            ],
        },
    },
]

WSGI_APPLICATION = 'cartera_clientes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de base de datos inteligente para producción y desarrollo
if os.environ.get('DB_ENGINE') == 'sqlite':
    # Configuración forzada para SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif os.environ.get('DB_NAME'):
    # Configuración de producción (MySQL) - Lee desde variables de entorno
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
        }
    }
else:
    # Configuración de desarrollo (SQLite) - Usada si no hay variables de entorno
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'app/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuración de URLs para autenticación (Añade o ajusta estas líneas al final) ---
# Estas URLs deben coincidir con las rutas que esperas bajo '/app/'
LOGIN_REDIRECT_URL = '/app/home/'    # Redirige aquí después de iniciar sesión
LOGIN_URL = '/app/login/'             # URL de tu página de inicio de sesión
LOGOUT_REDIRECT_URL = '/app/login/'   # Redirige aquí después de cerrar sesión

# cartera_clientes/settings.py

# ... otras configuraciones ...

# Configuración para WeasyPrint (opcional, pero buena práctica si usas rutas absolutas)
# import os
# WEASYPRINT_BASEURL = os.path.join(BASE_DIR, 'static/') # Si tienes archivos estáticos en 'static/'

# Para el formato de moneda en el filtro de Django (si no lo tienes ya)
USE_L10N = True
USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = '.'
THOUSAND_SEPARATOR = ','