# Generated by Django 5.2.4 on 2025-07-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cotizacion_tipo_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_visible',
            field=models.BooleanField(default=True, verbose_name='Mostrar Columna de Descuento'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='producto',
            field=models.CharField(choices=[('ZEBRA', 'ZEBRA'), ('PANDUIT', 'PANDUIT'), ('APC', 'APC'), ('AVIGILION', 'AVIGILION'), ('GENETEC', 'GENETEC'), ('AXIS', 'AXIS'), ('SOFTWARE', 'SOFTWARE'), ('RUNRATE', 'RUNRATE'), ('PÓLIZA', 'PÓLIZA'), ('CISCO', 'CISCO')], max_length=100, verbose_name='Producto / Servicio'),
        ),
    ]
