# Generated by Django 5.2.4 on 2025-07-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cotizacion_descuento_visible_alter_todoitem_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='marca',
            field=models.CharField(blank=True, choices=[('ZEBRA', 'ZEBRA'), ('PANDUIT', 'PANDUIT'), ('APC', 'APC'), ('AVIGILION', 'AVIGILION'), ('GENETEC', 'GENETEC'), ('AXIS', 'AXIS'), ('CISCO', 'CISCO')], max_length=50, null=True, verbose_name='Marca'),
        ),
    ]
