# Generated by Django 5.2.4 on 2025-07-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_detallecotizacion_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='bitrix_deal_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID de Oportunidad en Bitrix24'),
        ),
    ]
