# Generated by Django 5.2.4 on 2025-07-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_todoitem_bitrix_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='bitrix_company_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID de Compañía en Bitrix24'),
        ),
    ]
