# Generated by Django 5.2.4 on 2025-07-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_todoitem_bitrix_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='bitrix_stage_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Etapa en Bitrix24'),
        ),
    ]
