# Generated by Django 5.2.4 on 2025-07-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_todoitem_bitrix_stage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bitrix_company_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID de Compañía en Bitrix24'),
        ),
    ]
