# Generated by Django 5.2.4 on 2025-07-26 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='app.todoitem', verbose_name='Oportunidad de Venta'),
        ),
    ]
