# Generated by Django 5.2.4 on 2025-07-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_cotizacion_oportunidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Contacto')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del Contacto')),
                ('bitrix_contact_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID de Contacto en Bitrix24')),
                ('company_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Compañía en Bitrix24')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='app.contacto', verbose_name='Contacto del Cliente'),
        ),
    ]
