# Generated by Django 5.2.4 on 2025-07-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_contacto_alter_todoitem_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='app.cliente', verbose_name='Cliente Asociado'),
        ),
    ]
