# Generated by Django 5.2.4 on 2025-07-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_contacto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Empresa'),
        ),
    ]
