# Generated by Django 5.2.4 on 2025-07-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_cliente_nombre_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo de Entrega'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ganancia (%)'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='no_parte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Parte'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor'),
        ),
    ]
