# Generated by Django 5.2.4 on 2025-07-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_detallecotizacion_entrega_detallecotizacion_ganancia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='entrega',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='ganancia',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='proveedor',
        ),
    ]
