# Generated by Django 5.2.4 on 2026-02-10 19:20

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_solicitud_acceso_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use SeparateDatabaseAndState because on fresh databases the actividad_id
        # and user_id columns were already removed by squashed migrations 0037-0042
        # that no longer exist as files. Skipping the DB ops avoids the
        # "Can't DROP actividad_id; check that column/key exists" error.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='actividad_participantes',
                    name='actividad',
                ),
                migrations.RemoveField(
                    model_name='actividad_participantes',
                    name='user',
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='carpetaproyecto',
            name='unique_folder_name_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='compartirarchivo',
            name='unique_file_sharing_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='intercambionavidad',
            name='app_intercambionavidad_año_key',
        ),
        migrations.RemoveConstraint(
            model_name='participanteintercambio',
            name='app_participanteintercambio_intercambio_usuario_key',
        ),
        migrations.RemoveConstraint(
            model_name='solicitudaccesoproyecto',
            name='app_solicitud_unique_proyecto_usuario',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='oportunidades_ligadas',
            field=models.ManyToManyField(blank=True, related_name='proyectos_ligados', to='app.todoitem', verbose_name='Oportunidades Ligadas'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio_sesion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio de Sesión de Trabajo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meta_mensual',
            field=models.DecimalField(decimal_places=2, default=1500000, max_digits=12, verbose_name='Meta Mensual de Ventas'),
        ),
        migrations.AlterField(
            model_name='archivoproyecto',
            name='archivo',
            field=models.FileField(upload_to=app.models.archivo_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciada', 'Iniciada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='app.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='carpetaproyecto',
            unique_together={('proyecto', 'carpeta_padre', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='compartirarchivo',
            unique_together={('archivo', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='intercambionavidad',
            unique_together={('año',)},
        ),
        migrations.AlterUniqueTogether(
            name='participanteintercambio',
            unique_together={('intercambio', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='solicitudaccesoproyecto',
            unique_together={('proyecto', 'usuario_solicitante')},
        ),
        # Use SeparateDatabaseAndState + RunSQL IF EXISTS so the table drop
        # works regardless of whether the columns still exist or not.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS `app_actividad_participantes`",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Actividad_participantes',
                ),
            ],
        ),
    ]
