# Generated by Django 5.2.4 on 2026-02-11 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_add_meta_mensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='facturacion/')),
                ('mes', models.CharField(max_length=2)),
                ('anio', models.IntegerField()),
                ('total_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('datos_json', models.JSONField(blank=True, default=dict)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Facturación',
                'verbose_name_plural': 'Archivos de Facturación',
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
