# Generated by Django 5.2.4 on 2026-02-11 21:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_archivofacturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='meta_oportunidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Meta (Oportunidad)'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='monto_facturacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto de Facturación'),
        ),
    ]
