# Generated by Django 5.2.4 on 2026-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_todoitem_meta_oportunidad_todoitem_monto_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='meta_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Meta de facturación mensual para este cliente', max_digits=14, verbose_name='Meta Mensual'),
        ),
    ]
