# Generated by Django 5.2.4 on 2026-02-18 01:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_muropost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meta_cobrado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Meta Cobrado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meta_cotizado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Meta Cotizado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meta_oportunidades',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Meta Oportunidades'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='meta_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500000'), max_digits=12, verbose_name='Meta Facturado'),
        ),
        migrations.DeleteModel(
            name='MuroPost',
        ),
    ]
