# Generated by Django 5.2.4 on 2026-02-18 21:11

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_userprofile_meta_cobrado_userprofile_meta_cotizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaOportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('carpeta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='app.carpetaoportunidad')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_drive', to='app.todoitem')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('oportunidad', 'carpeta_padre', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ArchivoOportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=app.models.archivo_opp_upload_path)),
                ('tipo_archivo', models.CharField(choices=[('documento', 'Documento'), ('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('hoja_calculo', 'Hoja de Cálculo'), ('presentacion', 'Presentación'), ('pdf', 'PDF'), ('archivo_comprimido', 'Archivo Comprimido'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('tamaño', models.BigIntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_drive', to='app.todoitem')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='app.carpetaoportunidad')),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
