# Generated by Django 5.2.4 on 2026-02-18 21:47

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_chat_oportunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeoportunidad',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajeoportunidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.chat_imagen_upload_path),
        ),
        migrations.AddField(
            model_name='mensajeoportunidad',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='app.mensajeoportunidad'),
        ),
        migrations.AlterField(
            model_name='mensajeoportunidad',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
