# Generated by Django 5.2.4 on 2026-02-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_comentario_tarea_opp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tarea_opp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='app.tareaoportunidad', verbose_name='Tarea de Oportunidad'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('mencion', 'Mención en comentario'), ('respuesta', 'Respuesta a comentario'), ('comentario_oportunidad', 'Nuevo comentario en oportunidad'), ('proyecto_agregado', 'Agregado a proyecto'), ('tarea_participante', 'Agregado como participante a tarea'), ('tarea_observador', 'Agregado como observador a tarea'), ('sistema', 'Notificación del sistema'), ('tarea_opp_asignada', 'Tarea de oportunidad asignada'), ('tarea_opp_comentario', 'Comentario en tarea de oportunidad'), ('oportunidad_mensaje', 'Nuevo mensaje en oportunidad')], max_length=25, verbose_name='Tipo de Notificación'),
        ),
    ]
