# Generated by Django 5.2.4 on 2026-02-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_mailadjunto_datos_b64'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_generales', to='app.todoitem', verbose_name='Oportunidad'),
        ),
    ]
