# Generated by Django 5.2.4 on 2026-03-01 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_tarea_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('segundos_laborados', models.PositiveIntegerField(default=0)),
                ('pausado', models.BooleanField(default=False)),
                ('ultima_pausa', models.DateTimeField(blank=True, null=True)),
                ('segundos_pausa', models.PositiveIntegerField(default=0)),
                ('eficiencia_dia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EficienciaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('promedio_eficiencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tareas_completadas', models.PositiveIntegerField(default=0)),
                ('actividades_completadas', models.PositiveIntegerField(default=0)),
                ('oportunidades_cobradas', models.PositiveIntegerField(default=0)),
                ('empleado_del_mes', models.BooleanField(default=False)),
                ('anuncio_publicado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eficiencias_mensuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eficiencia Mensual',
                'verbose_name_plural': 'Eficiencias Mensuales',
                'unique_together': {('usuario', 'mes', 'anio')},
            },
        ),
    ]
