# Generated by Django 5.2.4 on 2026-03-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_asistenciajornada_eficienciamensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('mencion', 'Mención en comentario'), ('respuesta', 'Respuesta a comentario'), ('comentario_oportunidad', 'Nuevo comentario en oportunidad'), ('proyecto_agregado', 'Agregado a proyecto'), ('tarea_participante', 'Agregado como participante a tarea'), ('tarea_observador', 'Agregado como observador a tarea'), ('sistema', 'Notificación del sistema'), ('tarea_opp_asignada', 'Tarea de oportunidad asignada'), ('tarea_opp_comentario', 'Comentario en tarea de oportunidad'), ('oportunidad_mensaje', 'Nuevo mensaje en oportunidad'), ('muro_mencion', 'Mención en el muro'), ('muro_post', 'Nuevo anuncio en el muro'), ('rendimiento_bajo', 'Bajo rendimiento de usuario')], max_length=25, verbose_name='Tipo de Notificación'),
        ),
    ]
