# Generated by Django 5.2.4 on 2026-03-01 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_notificacion_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('mencion', 'Mención en comentario'), ('respuesta', 'Respuesta a comentario'), ('comentario_oportunidad', 'Nuevo comentario en oportunidad'), ('proyecto_agregado', 'Agregado a proyecto'), ('tarea_participante', 'Agregado como participante a tarea'), ('tarea_observador', 'Agregado como observador a tarea'), ('sistema', 'Notificación del sistema'), ('tarea_opp_asignada', 'Tarea de oportunidad asignada'), ('tarea_opp_comentario', 'Comentario en tarea de oportunidad'), ('oportunidad_mensaje', 'Nuevo mensaje en oportunidad'), ('muro_mencion', 'Mención en el muro'), ('muro_post', 'Nuevo anuncio en el muro'), ('rendimiento_bajo', 'Bajo rendimiento de usuario'), ('solicitud_cambio_perfil', 'Solicitud de cambio de perfil')], max_length=25, verbose_name='Tipo de Notificación'),
        ),
        migrations.CreateModel(
            name='SolicitudCambioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('language', models.CharField(blank=True, max_length=2)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/solicitudes/')),
                ('old_first_name', models.CharField(blank=True, max_length=150)),
                ('old_last_name', models.CharField(blank=True, max_length=150)),
                ('old_email', models.EmailField(blank=True, max_length=254)),
                ('old_language', models.CharField(blank=True, max_length=2)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('procesada', models.BooleanField(default=False)),
                ('aprobada', models.BooleanField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True, null=True)),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_perfil_autorizados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Perfil',
                'verbose_name_plural': 'Solicitudes de Cambio de Perfil',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
