# Generated by Django 5.2.4 on 2026-03-01 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_notificacion_tipo_solicitudcambioperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='solicitud_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='app.solicitudcambioperfil'),
        ),
    ]
