# Generated by Django 5.2.4 on 2026-03-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_notificacion_solicitud_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('perla', 'Perla'), ('sakura', 'Sakura'), ('duna', 'Duna'), ('espacial', 'Espacial')], default='perla', max_length=20, verbose_name='Tema de color'),
        ),
    ]
