# Generated by Django 5.2.4 on 2026-03-03 17:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_archivooportunidad_bitrix_fields_tareaoportunidad_bitrix_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tiene_archivos_po',
            field=models.BooleanField(default=False, verbose_name='Tiene archivos PO en Drive'),
        ),
        migrations.AlterField(
            model_name='archivooportunidad',
            name='archivo',
            field=models.FileField(blank=True, upload_to=app.models.archivo_opp_upload_path),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tipo_negociacion',
            field=models.CharField(choices=[('runrate', 'Runrate'), ('proyecto', 'Proyecto'), ('bitrix_proyecto', 'Proyecto Bitrix24')], default='runrate', max_length=20, verbose_name='Tipo de Negociación'),
        ),
    ]
