# Generated by Django 5.2.4 on 2026-03-03 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_bitrix_proyecto_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('ingeniero', 'Ingeniero')], default='vendedor', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='IngenieroBoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('fecha_planeada', models.DateField(blank=True, null=True, verbose_name='Fecha planeada por el ingeniero')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_items', to='app.tarea')),
                ('tarea_opp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_items', to='app.tareaoportunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Tablero Ingeniero',
                'verbose_name_plural': 'Items Tablero Ingeniero',
                'ordering': ['orden'],
            },
        ),
    ]
