# Generated by Django 5.2.4 on 2026-03-05 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_ingeniero_rol_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_key', models.CharField(help_text='Key del item (ej: proy_1, opp_123, gen_45)', max_length=100, verbose_name='Clave del proyecto/tarea')),
                ('titulo', models.CharField(max_length=255, verbose_name='Descripción de la actividad')),
                ('dia_semana', models.CharField(help_text='Lunes, Martes, Miércoles, Jueves, Viernes', max_length=20, verbose_name='Día de la semana')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha específica')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_programadas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('responsables', models.ManyToManyField(blank=True, related_name='actividades_programadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsables')),
            ],
            options={
                'verbose_name': 'Actividad Programada',
                'verbose_name_plural': 'Actividades Programadas',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
