# Generated by Django 5.2.4 on 2026-03-06 19:18

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_proyectos_ingenieria_bitrix_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoproyecto',
            name='archivo',
            field=models.FileField(blank=True, upload_to=app.models.archivo_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='empleadodelmes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='mailconexion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_conexion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('mencion', 'Mención en comentario'), ('respuesta', 'Respuesta a comentario'), ('comentario_oportunidad', 'Nuevo comentario en oportunidad'), ('proyecto_agregado', 'Agregado a proyecto'), ('tarea_participante', 'Agregado como participante a tarea'), ('tarea_observador', 'Agregado como observador a tarea'), ('sistema', 'Notificación del sistema'), ('tarea_opp_asignada', 'Tarea de oportunidad asignada'), ('tarea_opp_comentario', 'Comentario en tarea de oportunidad'), ('oportunidad_mensaje', 'Nuevo mensaje en oportunidad'), ('muro_mencion', 'Mención en el muro'), ('muro_post', 'Nuevo anuncio en el muro'), ('rendimiento_bajo', 'Bajo rendimiento de usuario'), ('solicitud_cambio_perfil', 'Solicitud de cambio de perfil'), ('programacion_proyecto', 'Asignado a actividad de proyecto')], max_length=25, verbose_name='Tipo de Notificación'),
        ),
        migrations.AlterField(
            model_name='programacionactividad',
            name='dia_semana',
            field=models.CharField(help_text='Lunes, Martes, Miércoles, Jueves, Viernes, Sábado, Domingo', max_length=20, verbose_name='Día de la semana'),
        ),
    ]
