# Generated by Django 5.2.4 on 2026-03-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_alter_empleadodelmes_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcorreo',
            name='conexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correos', to='app.mailconexion'),
        ),
    ]
