# Generated by Django 5.2.4 on 2026-03-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_cliente_meta_cobrado_meta_cotizado_meta_oportunidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='completada',
            field=models.BooleanField(default=False, verbose_name='Completada'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='meta_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Meta de facturación mensual para este cliente', max_digits=14, verbose_name='Meta Facturado'),
        ),
        migrations.AlterField(
            model_name='novedadesconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
