# Generated by Django 5.2.4 on 2026-03-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_alter_notificacion_tipo_max_length'),
        ('app', '0093_mailcorreo_destacado_eliminado'),
    ]

    operations = [
    ]
