# Generated by Django 5.2.4 on 2026-03-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_merge_20260320_1134'),
        ('app', '0094_reglaautomatizacion_ejecucionautomatizacion'),
    ]

    operations = [
    ]
