# Generated by Django 5.2.4 on 2026-03-23 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_grupotrabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensaje', 'Mensaje'), ('sistema', 'Sistema')], default='mensaje', max_length=10)),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('accion', models.CharField(blank=True, default='', max_length=60, verbose_name='Acción (sistema)')),
                ('objeto_tipo', models.CharField(blank=True, default='', max_length=30, verbose_name='Tipo de objeto referenciado')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto referenciado')),
                ('objeto_titulo', models.CharField(blank=True, default='', max_length=255, verbose_name='Título del objeto referenciado')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_grupo', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='app.grupotrabajo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Mensaje de Grupo',
                'verbose_name_plural': 'Mensajes de Grupo',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='LecturaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='app.grupotrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_grupo', to=settings.AUTH_USER_MODEL)),
                ('ultimo_leido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mensajegrupo')),
            ],
            options={
                'verbose_name': 'Lectura de Grupo',
                'unique_together': {('usuario', 'grupo')},
            },
        ),
    ]
