# Generated by Django 5.2.4 on 2026-03-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_mensajegrupo_lecturagrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionautomatizacion',
            name='tarea_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_automatizacion', to='app.tarea', verbose_name='Tarea general creada'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='avanzar_etapa_al_completar',
            field=models.BooleanField(default=False, help_text='Al completar la tarea creada por esta regla, avanzar automaticamente la oportunidad a la siguiente etapa', verbose_name='Avanzar etapa al completar'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='regla_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to='app.reglaautomatizacion', verbose_name='Regla de automatizacion que creo esta tarea'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('tarea_vencida', 'Tarea vencida'), ('tarea_por_vencer', 'Tarea por vencer'), ('actividad_vencida', 'Actividad vencida'), ('actividad_por_vencer', 'Actividad por vencer'), ('rendimiento_bajo', 'Bajo rendimiento de usuario'), ('tarea_reprogramada', 'Tarea reprogramada'), ('tarea_asignada', 'Tarea asignada'), ('tarea_opp_asignada', 'Tarea de oportunidad asignada'), ('mencion', 'Mención en comentario'), ('muro_mencion', 'Mención en el muro'), ('tarea_mencion', 'Mención en tarea'), ('solicitud_cambio_perfil', 'Solicitud de cambio de perfil'), ('tarea_participante', 'Agregado como participante a tarea'), ('tarea_observador', 'Agregado como observador a tarea'), ('comentario_oportunidad', 'Nuevo comentario en oportunidad'), ('tarea_comentario', 'Comentario en tarea'), ('tarea_opp_comentario', 'Comentario en tarea de oportunidad'), ('oportunidad_mensaje', 'Nuevo mensaje en oportunidad'), ('muro_post', 'Nuevo anuncio en el muro'), ('respuesta', 'Respuesta a comentario'), ('sistema', 'Notificación del sistema'), ('proyecto_agregado', 'Agregado a proyecto'), ('programacion_proyecto', 'Asignado a actividad de proyecto'), ('mensaje_grupo', 'Mensaje en grupo de trabajo')], max_length=30, verbose_name='Tipo de Notificación'),
        ),
    ]
