# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_cadena_reactiva_automatizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meta_cotizado_numero',
            field=models.IntegerField(default=0, verbose_name='Meta Cotizado (Numero)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='meta_cotizado_numero',
            field=models.IntegerField(default=0, verbose_name='Meta Cotizado (Numero)'),
        ),
    ]
