# Generated by Django 5.2.4 on 2026-03-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_proyectos_iamet'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoiamet',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_iamet_vinculados', to='app.todoitem'),
        ),
    ]
