# Generated by Django 5.2.4 on 2026-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_add_oportunidad_to_proyectoiamet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='RFC'),
        ),
    ]
