# Generated by Django 5.2.4 on 2026-03-25 21:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_add_rfc_to_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoVolumetriaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('archivo_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_costo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_venta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('ganancia', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('margen', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('num_partidas', models.PositiveIntegerField(default=0)),
                ('partidas_json', models.JSONField(blank=True, default=list)),
                ('notas', models.TextField(blank=True, default='')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones_volumetria', to='app.proyectoiamet')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version de Volumetria',
                'verbose_name_plural': 'Versiones de Volumetria',
                'ordering': ['-version'],
                'unique_together': {('proyecto', 'version')},
            },
        ),
    ]
