# Generated by Django 5.2.4

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0104_prospeccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('bloques_json', models.JSONField(blank=True, default=list)),
                ('html_rendered', models.TextField(blank=True, default='')),
                ('color_primario', models.CharField(default='#0052D4', max_length=7)),
                ('color_fondo', models.CharField(default='#F5F5F7', max_length=7)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('asunto', models.CharField(blank=True, default='', max_length=200)),
                ('es_plantilla_sistema', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campana_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Campaña',
                'verbose_name_plural': 'Templates de Campaña',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('asunto', models.CharField(max_length=200)),
                ('html_final', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('enviando', 'Enviando'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('destinatarios_json', models.JSONField(blank=True, default=list)),
                ('total_enviados', models.IntegerField(default=0)),
                ('total_abiertos', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('producto', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='app.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='app.prospecto')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.campanatemplate')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
