# Generated by Django 5.2.4 on 2026-04-01 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_alter_etapapipeline_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.CharField(help_text='Nombre o palabra que aparece en el Excel/CSV', max_length=100, unique=True)),
                ('buscar_como', models.CharField(help_text='Nombre del cliente en el CRM para hacer el match', max_length=100)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Alias de Cliente',
                'verbose_name_plural': 'Alias de Clientes',
            },
        ),
        migrations.AlterField(
            model_name='campanaenvio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='meta_cotizado_numero',
            field=models.IntegerField(default=0, verbose_name='Meta Cotizado (Numero)'),
        ),
        migrations.AlterField(
            model_name='etapapipeline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prospectoactividad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prospectocomentario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='meta_cotizado_numero',
            field=models.IntegerField(default=0, verbose_name='Meta Cotizado (Numero)'),
        ),
        migrations.CreateModel(
            name='ArchivoCobrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cobrado/')),
                ('mes', models.CharField(max_length=2)),
                ('anio', models.IntegerField()),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('datos_json', models.JSONField(blank=True, default=dict)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de Cobrado',
                'verbose_name_plural': 'Archivos de Cobrado',
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
