# Generated by Django 5.2.4 on 2026-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_aliascliente_alter_campanaenvio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadesconfig',
            name='em_activation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novedadesconfig',
            name='em_widget_activo',
            field=models.BooleanField(default=False),
        ),
    ]
