# Generated by Django 5.2.4 on 2026-08-19 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0216_cliente_es_prospecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', help_text='ID del lead en la plataforma web, para no duplicar en reintentos.', max_length=100)),
                ('fuente', models.CharField(choices=[('form', 'Formulario de contacto'), ('agent', 'Agente virtual'), ('advisor', 'Tech Advisor'), ('quote', 'Cotización de tienda'), ('academy', 'Academia'), ('otro', 'Otro')], default='form', max_length=20)),
                ('empresa', models.CharField(blank=True, default='', max_length=200)),
                ('nombre_contacto', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('procesado', 'Procesado'), ('duplicado', 'Duplicado'), ('error', 'Error')], default='procesado', max_length=15)),
                ('error', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Web',
                'verbose_name_plural': 'Leads Web',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LeadWebConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('notificar_supervisores', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Leads Web',
                'verbose_name_plural': 'Configuración de Leads Web',
            },
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('tarea_vencida', 'Tarea vencida'), ('tarea_por_vencer', 'Tarea por vencer'), ('actividad_vencida', 'Actividad vencida'), ('actividad_por_vencer', 'Actividad por vencer'), ('actividad_opp_vencida', 'Actividad de oportunidad vencida'), ('actividad_opp_por_vencer', 'Actividad de oportunidad por vencer'), ('rendimiento_bajo', 'Bajo rendimiento de usuario'), ('tarea_completada', 'Tarea completada'), ('tarea_reabierta', 'Tarea reabierta'), ('tarea_reprogramada', 'Tarea reprogramada'), ('tarea_asignada', 'Tarea asignada'), ('tarea_opp_asignada', 'Tarea de oportunidad asignada'), ('mencion', 'Mención en comentario'), ('muro_mencion', 'Mención en el muro'), ('tarea_mencion', 'Mención en tarea'), ('solicitud_cambio_perfil', 'Solicitud de cambio de perfil'), ('tarea_participante', 'Agregado como participante a tarea'), ('tarea_observador', 'Agregado como observador a tarea'), ('comentario_oportunidad', 'Nuevo comentario en oportunidad'), ('tarea_comentario', 'Comentario en tarea'), ('tarea_opp_comentario', 'Comentario en tarea de oportunidad'), ('oportunidad_mensaje', 'Nuevo mensaje en oportunidad'), ('muro_post', 'Nuevo anuncio en el muro'), ('respuesta', 'Respuesta a comentario'), ('sistema', 'Notificación del sistema'), ('proyecto_agregado', 'Agregado a proyecto'), ('programacion_proyecto', 'Asignado a actividad de proyecto'), ('mensaje_grupo', 'Mensaje en grupo de trabajo'), ('prospecto_asignado', 'Prospecto asignado por supervisor'), ('lead_web', 'Lead desde la página web'), ('certificacion_por_vencer', 'Certificación por vencer'), ('certificacion_vencida', 'Certificación vencida')], max_length=30, verbose_name='Tipo de Notificación'),
        ),
        migrations.AddField(
            model_name='leadweb',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_web', to='app.cliente'),
        ),
        migrations.AddField(
            model_name='leadweb',
            name='prospecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_web', to='app.prospecto'),
        ),
        migrations.AddField(
            model_name='leadwebconfig',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario al que se asignan los prospectos que llegan de la web.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_web_asignados', to=settings.AUTH_USER_MODEL),
        )
    ]
