# Generated by Django 5.2.4 on 2026-08-19 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0217_leads_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='prospecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app.prospecto', verbose_name='Prospecto relacionado'),
        ),
        migrations.AlterField(
            model_name='avisopospuesto',
            name='tipo',
            field=models.CharField(choices=[('correo', 'Correo'), ('oportunidad', 'Oportunidad'), ('lead', 'Lead web')], max_length=12),
        ),
    ]
