# Generated by Django 5.2.4 on 2026-08-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0218_leads_web_notifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadweb',
            name='sitio',
            field=models.ForeignKey(blank=True, help_text='Sitio/página del que llegó el lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='app.leadwebconfig'),
        ),
        migrations.AddField(
            model_name='leadwebconfig',
            name='nombre',
            field=models.CharField(default='iamet.mx', help_text='Nombre del sitio/página que manda los leads.', max_length=80),
        ),
    ]
