# Generated by Django 5.2.4 on 2026-08-21
# Filtrada a mano: solo el alta de la choice CURSO en producto
# (todoitem, prospecto, productooportunidad). El drift preexistente de
# RenameIndex/AlterField id NO va aquí.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0219_leads_web_sitios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productooportunidad',
            name='producto',
            field=models.CharField(choices=[('ZEBRA', 'ZEBRA'), ('PANDUIT', 'PANDUIT'), ('APC', 'APC'), ('AVIGILION', 'AVIGILION'), ('GENETEC', 'GENETEC'), ('AXIS', 'AXIS'), ('SOFTWARE', 'SOFTWARE'), ('RUNRATE', 'RUNRATE'), ('PÓLIZA', 'PÓLIZA'), ('CISCO', 'CISCO'), ('SERVICIO', 'Servicio'), ('CURSO', 'Curso')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='producto',
            field=models.CharField(choices=[('ZEBRA', 'ZEBRA'), ('PANDUIT', 'PANDUIT'), ('APC', 'APC'), ('AVIGILION', 'AVIGILION'), ('GENETEC', 'GENETEC'), ('AXIS', 'AXIS'), ('SOFTWARE', 'SOFTWARE'), ('RUNRATE', 'RUNRATE'), ('PÓLIZA', 'PÓLIZA'), ('CISCO', 'CISCO'), ('SERVICIO', 'Servicio'), ('CURSO', 'Curso')], default='ZEBRA', max_length=100),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='producto',
            field=models.CharField(choices=[('ZEBRA', 'ZEBRA'), ('PANDUIT', 'PANDUIT'), ('APC', 'APC'), ('AVIGILION', 'AVIGILION'), ('GENETEC', 'GENETEC'), ('AXIS', 'AXIS'), ('SOFTWARE', 'SOFTWARE'), ('RUNRATE', 'RUNRATE'), ('PÓLIZA', 'PÓLIZA'), ('CISCO', 'CISCO'), ('SERVICIO', 'Servicio'), ('CURSO', 'Curso')], default='ZEBRA', max_length=100, verbose_name='Producto / Servicio'),
        ),
    ]
