name: Deploy a Pruebas

on:
  push:
    branches:
      - pruebas

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/iamet2026/crm-pruebas
            git pull origin pruebas
            sudo docker compose --env-file .env.pruebas -f docker-compose.pruebas.yml exec -T web python manage.py collectstatic --noinput
            sudo docker compose --env-file .env.pruebas -f docker-compose.pruebas.yml restart web
